name: Multi-Cloud CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./terraform

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.27.0'

      - name: Deploy to Kubernetes
        run: kubectl apply -f ./k8s/
